// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fklzpllfylwtelayuuth.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZrbHpwbGxmeWx3dGVsYXl1dXRoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NTQxODYsImV4cCI6MjA2NTUzMDE4Nn0.cp3WIHWxWItni1a2WHq5LCIdHcrBnb4U9uyR2FvmLEE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);